#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_GROUPS="${OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_GROUPS:-${OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_DIAGNOSTIC_GROUPS:-runtime-adapter-module}}"
export OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_PORT_BASE="${OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_PORT_BASE:-29920}"
export OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_RUN_ID="${OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_RUN_ID:-pre-credential-pair-batch-diagnostics-$$}"
export OPENCLAW_RUNTIME_PROFILE="${OPENCLAW_RUNTIME_PROFILE:-true}"
export OPENCLAW_RUNTIME_PROFILE_FILE="${OPENCLAW_RUNTIME_PROFILE_FILE:-$SCRIPT_DIR/../../.artifacts/$OPENCLAW_LIVE_PROVIDER_PRE_CREDENTIAL_PAIR_BATCH_RUN_ID-runtime-profile.jsonl}"

bash "$SCRIPT_DIR/dev-openclaw-live-provider-pre-credential-pair-batch-reuse-check.sh"
