#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ARTIFACT_DIR="$REPO_ROOT/.artifacts/milestone-check"

mkdir -p "$ARTIFACT_DIR"

checks=(
  "body-config|dev-body-config-check.sh|NixOS body module, profiles, and systemd service skeleton"
  "state-settling|dev-state-settling-check.sh|Session/browser/screen first-frame settling"
  "openclaw-ai-work-view-capture|dev-openclaw-ai-work-view-capture-check.sh|Browser-runtime-backed AI work view capture metadata through screen-sense"
  "openclaw-ai-work-view-capture-summary|dev-openclaw-ai-work-view-capture-summary-check.sh|Structured AI work view capture summaries through browser-runtime and screen-sense"
  "openclaw-ai-work-view-task-verification-summary|dev-openclaw-ai-work-view-task-verification-summary-check.sh|Task verification records AI work view summary evidence"
  "openclaw-eye-hand-action-evidence|dev-openclaw-eye-hand-action-evidence-check.sh|Task verification links screen actions to final AI work view observations"
  "openclaw-eye-hand-recovery-evidence|dev-openclaw-eye-hand-recovery-evidence-check.sh|Failed task recovery evidence references eye-hand action and observation context"
  "openclaw-eye-hand-auto-recovery-execution|dev-openclaw-eye-hand-auto-recovery-execution-check.sh|Auto recovery executes using eye-hand recovery recommendation targets"
  "openclaw-eye-hand-recovery-regression|dev-openclaw-eye-hand-recovery-regression-check.sh|Focused regression for the AI work view eye-hand recovery loop"
  "openclaw-mvp-route-alignment|dev-openclaw-mvp-route-alignment-check.sh|Whitepaper-aligned MVP route checkpoint after the eye-hand recovery loop"
  "openclaw-system-health-self-heal-evidence|dev-openclaw-system-health-self-heal-evidence-check.sh|Body health snapshot drives conservative self-heal evidence"
  "openclaw-mvp-readiness|dev-openclaw-mvp-readiness-check.sh|First-stage MVP readiness regression across body, eyes, hands, recovery, and self-heal"
  "openclaw-mvp-status|dev-openclaw-mvp-status-check.sh|First-stage MVP status, demo path, and next-phase boundary"
  "openclaw-mvp-demo-guide|dev-openclaw-mvp-demo-guide-check.sh|First-stage MVP human demo guide and evidence checklist"
  "openclaw-mvp-release-exit|dev-openclaw-mvp-release-exit-check.sh|First-stage MVP release exit gate"
  "openclaw-phase-2-plan|dev-openclaw-phase-2-plan-check.sh|Whitepaper-aligned Phase 2 route selection"
  "openclaw-systemd-unit-inventory|dev-openclaw-systemd-unit-inventory-check.sh|Read-only OpenClaw systemd unit inventory for Phase 2 body governance"
  "openclaw-systemd-repair-plan|dev-openclaw-systemd-repair-plan-check.sh|Plan-only systemd repair proposal for one OpenClaw body unit"
  "openclaw-systemd-repair-dry-run|dev-openclaw-systemd-repair-dry-run-check.sh|Operator-visible dry-run envelope for OpenClaw systemd repair proposals"
  "openclaw-systemd-repair-execution-route|dev-openclaw-systemd-repair-execution-route-check.sh|Route gate for operator-reviewed real OpenClaw systemd repair execution"
  "openclaw-systemd-repair-execution-task|dev-openclaw-systemd-repair-execution-task-check.sh|Approval-gated operator-reviewed systemd repair execution task shell"
  "openclaw-systemd-repair-approved-deferred|dev-openclaw-systemd-repair-approved-deferred-check.sh|Approved operator flow remains deferred before real OpenClaw systemd repair execution"
  "openclaw-systemd-repair-real-execution|dev-openclaw-systemd-repair-real-execution-check.sh|Operator-approved real OpenClaw systemd repair execution attempt"
  "openclaw-systemd-repair-post-verification|dev-openclaw-systemd-repair-post-verification-check.sh|Post-execution body-state verification for real OpenClaw systemd repair"
  "openclaw-phase-2-repair-demo-status|dev-openclaw-phase-2-repair-demo-status-check.sh|Read-only Phase 2 repair demo status and evidence bundle"
  "openclaw-systemd-repair-auth-delegation|dev-openclaw-systemd-repair-auth-delegation-check.sh|Narrow passwordless authorization bridge for approved OpenClaw systemd repair"
  "openclaw-body-service-dependency-map|dev-openclaw-body-service-dependency-map-check.sh|Read-only OpenClaw body service dependency map for Phase 2 governance"
  "openclaw-health-trend-summary|dev-openclaw-health-trend-summary-check.sh|Read-only health trend summary from recent OpenClaw body snapshots"
  "openclaw-route-aware-next-action-recommendation|dev-openclaw-route-aware-next-action-recommendation-check.sh|Read-only route-aware next-action recommendation from body governance evidence"
  "openclaw-conservative-recovery-policy-explanation|dev-openclaw-conservative-recovery-policy-explanation-check.sh|Read-only conservative recovery policy explanation from body governance evidence"
  "openclaw-body-governance-readiness|dev-openclaw-body-governance-readiness-check.sh|Read-only Phase 2 Track C body governance readiness bundle"
  "openclaw-body-evidence-timeline|dev-openclaw-body-evidence-timeline-check.sh|Read-only Phase 2 body evidence timeline"
  "openclaw-body-evidence-timeline-readiness|dev-openclaw-body-evidence-timeline-readiness-check.sh|Read-only Phase 2 body evidence timeline readiness"
  "openclaw-body-evidence-ledger-plan|dev-openclaw-body-evidence-ledger-plan-check.sh|Plan-only Phase 2 body evidence ledger design"
  "openclaw-body-evidence-ledger-route-review|dev-openclaw-body-evidence-ledger-route-review-check.sh|Read-only Phase 2 body evidence ledger implementation route review"
  "openclaw-body-evidence-ledger-storage-root-plan|dev-openclaw-body-evidence-ledger-storage-root-plan-check.sh|Plan-only Phase 2 body evidence ledger storage root selection"
  "openclaw-body-evidence-ledger-storage-root-route-review|dev-openclaw-body-evidence-ledger-storage-root-route-review-check.sh|Read-only Phase 2 body evidence ledger storage root materialization route review"
  "openclaw-body-evidence-ledger-directory-task|dev-openclaw-body-evidence-ledger-directory-task-check.sh|Approval-gated Phase 2 body evidence ledger directory task shell"
  "openclaw-body-evidence-ledger-directory-execution|dev-openclaw-body-evidence-ledger-directory-execution-check.sh|Approved Phase 2 body evidence ledger directory creation"
  "openclaw-body-evidence-ledger-first-record-plan|dev-openclaw-body-evidence-ledger-first-record-plan-check.sh|Plan-only Phase 2 body evidence ledger first record"
  "openclaw-body-evidence-ledger-first-record-route-review|dev-openclaw-body-evidence-ledger-first-record-route-review-check.sh|Read-only Phase 2 body evidence ledger first record route review"
  "openclaw-body-evidence-ledger-first-record-task|dev-openclaw-body-evidence-ledger-first-record-task-check.sh|Approval-gated Phase 2 body evidence ledger first record task shell"
  "openclaw-body-evidence-ledger-first-record-append|dev-openclaw-body-evidence-ledger-first-record-append-check.sh|Approved Phase 2 body evidence ledger first record append"
  "openclaw-body-evidence-ledger-readiness|dev-openclaw-body-evidence-ledger-readiness-check.sh|Read-only Phase 2 body evidence ledger readiness"
  "openclaw-body-evidence-ledger-demo-status|dev-openclaw-body-evidence-ledger-demo-status-check.sh|Read-only Phase 2 body evidence ledger demo status"
  "openclaw-phase-2-route-review|dev-openclaw-phase-2-route-review-check.sh|Whitepaper-aligned Phase 2 route review after Track C readiness"
  "openclaw-phase-2-demo-control-room|dev-openclaw-phase-2-demo-control-room-check.sh|Read-only Phase 2 operator demo control room"
  "openclaw-phase-2-demo-walkthrough|dev-openclaw-phase-2-demo-walkthrough-check.sh|Read-only Phase 2 human demo walkthrough"
  "openclaw-phase-2-demo-readiness-exit|dev-openclaw-phase-2-demo-readiness-exit-check.sh|Read-only Phase 2 demo readiness exit gate"
  "openclaw-phase-2-next-capability-route-review|dev-openclaw-phase-2-next-capability-route-review-check.sh|Whitepaper-aligned next Phase 2 body capability route review"
  "openclaw-phase-2-next-capability-route-review-ledger-ready|dev-openclaw-phase-2-next-capability-route-review-ledger-ready-check.sh|Whitepaper-aligned next Phase 2 route review after body evidence ledger readiness"
  "openclaw-phase-2-next-capability-route-review-ledger-demo-ready|dev-openclaw-phase-2-next-capability-route-review-ledger-demo-ready-check.sh|Whitepaper-aligned next Phase 2 route review after body evidence ledger demo readiness"
  "openclaw-systemd-next-repair-scope-review|dev-openclaw-systemd-next-repair-scope-review-check.sh|Read-only next OpenClaw systemd repair scope review after ledger demo status"
  "openclaw-systemd-next-repair-plan|dev-openclaw-systemd-next-repair-plan-check.sh|Plan-only next OpenClaw systemd repair scope after ledger demo status"
  "openclaw-systemd-next-repair-route-review|dev-openclaw-systemd-next-repair-route-review-check.sh|Read-only route review for the next OpenClaw systemd repair dry-run"
  "openclaw-systemd-next-repair-dry-run|dev-openclaw-systemd-next-repair-dry-run-check.sh|Operator-visible dry-run envelope for the next OpenClaw systemd repair"
  "openclaw-systemd-next-repair-task-route|dev-openclaw-systemd-next-repair-task-route-check.sh|Read-only task route for the next OpenClaw systemd repair"
  "openclaw-systemd-next-repair-task-shell|dev-openclaw-systemd-next-repair-task-shell-check.sh|Approval-gated task shell for the next OpenClaw systemd repair"
  "openclaw-systemd-next-repair-real-execution|dev-openclaw-systemd-next-repair-real-execution-check.sh|Operator-approved real execution attempt for the next OpenClaw systemd repair"
  "openclaw-systemd-repair-candidate-assessment|dev-openclaw-systemd-repair-candidate-assessment-check.sh|Read-only OpenClaw systemd repair candidate assessment"
  "openclaw-systemd-repair-candidate-plan|dev-openclaw-systemd-repair-candidate-plan-check.sh|Plan-only OpenClaw systemd repair candidate scope"
  "openclaw-systemd-repair-candidate-task-route|dev-openclaw-systemd-repair-candidate-task-route-check.sh|Read-only OpenClaw systemd repair candidate task route gate"
  "openclaw-systemd-repair-candidate-task-shell|dev-openclaw-systemd-repair-candidate-task-shell-check.sh|Approval-gated OpenClaw systemd repair candidate task shell"
  "openclaw-systemd-repair-candidate-readiness|dev-openclaw-systemd-repair-candidate-readiness-check.sh|Read-only OpenClaw systemd repair candidate block readiness"
  "openclaw-systemd-repair-candidate-route-review|dev-openclaw-systemd-repair-candidate-route-review-check.sh|Whitepaper-aligned route review after OpenClaw systemd repair candidate readiness"
  "openclaw-systemd-repair-candidate-demo-status|dev-openclaw-systemd-repair-candidate-demo-status-check.sh|Read-only OpenClaw systemd repair candidate demo status"
  "task-workbench|dev-task-workbench-check.sh|Task lifecycle, recovery, history, and work view coordination"
  "task-executor|dev-task-executor-check.sh|Executor verification, failed checks, manual and auto recovery"
  "persistence|dev-persistence-check.sh|Core task state persistence and recovery chains"
  "planner|dev-planner-check.sh|Rule planner plan-only and planned execution flows"
  "operator-loop|dev-operator-loop-check.sh|Operator step/run queue consumption and persistence"
  "operator-control|dev-operator-control-check.sh|Operator state, dry-run, pause gate, and resume control"
  "policy|dev-policy-check.sh|Policy governance, audit, and cross-boundary execution gate"
  "sovereign-body-policy|dev-sovereign-body-policy-check.sh|Sovereign body autonomy for body-internal capability governance"
  "sovereign-command-execute|dev-sovereign-command-execute-check.sh|Sovereign body execution of allowlisted system commands"
  "sovereign-command-chain|dev-sovereign-command-chain-check.sh|Sovereign body command chains with persisted transcripts"
  "sovereign-command-branch|dev-sovereign-command-branch-check.sh|Sovereign body command branching from previous transcripts"
  "sovereign-command-recovery|dev-sovereign-command-recovery-check.sh|Sovereign body command recovery from non-zero exit codes"
  "sovereign-command-ledger|dev-sovereign-command-ledger-check.sh|Sovereign body command transcript ledger and restart recovery"
  "sovereign-maintenance|dev-sovereign-maintenance-check.sh|Sovereign body autonomous maintenance through conservative heal runs"
  "sovereign-maintenance-scheduler|dev-sovereign-maintenance-scheduler-check.sh|Sovereign body maintenance policy, ticks, and scheduler persistence"
  "sovereign-filesystem-write|dev-sovereign-filesystem-write-check.sh|Sovereign body bounded filesystem text writes"
  "sovereign-filesystem-workspace|dev-sovereign-filesystem-workspace-check.sh|Sovereign body filesystem workspace creation chain"
  "sovereign-filesystem-append|dev-sovereign-filesystem-append-check.sh|Sovereign body bounded filesystem text appends"
  "sovereign-filesystem-ledger|dev-sovereign-filesystem-ledger-check.sh|Sovereign body filesystem change ledger and restart recovery"
  "sovereign-filesystem-read-text|dev-sovereign-filesystem-read-text-check.sh|Sovereign body bounded filesystem text readback"
  "sovereign-filesystem-read-ledger|dev-sovereign-filesystem-read-ledger-check.sh|Sovereign body filesystem read access ledger and restart recovery"
  "approval|dev-approval-check.sh|Approval inbox, user decisions, and operator approval gate"
  "capability|dev-capability-check.sh|Body capability registry, risks, health, and approval boundaries"
  "capability-planner|dev-capability-planner-check.sh|Capability-aware planning with risk and governance metadata"
  "capability-invoke|dev-capability-invoke-check.sh|Policy-governed capability invocation through core"
  "capability-history|dev-capability-history-check.sh|Persistent capability invocation history and restart recovery"
  "capability-operator|dev-capability-operator-check.sh|Operator execution through governed capability invocation"
  "capability-approval-operator|dev-capability-approval-operator-check.sh|Operator waits for user approval before high-risk capability execution"
  "event-audit|dev-event-audit-check.sh|Durable event audit ledger, filters, summary, and restart recovery"
  "system-capability|dev-system-capability-check.sh|Conservative filesystem, process, and command dry-run capabilities"
  "system-sense|dev-system-sense-check.sh|Real body vitals, service latency, resources, and alerts"
  "system-heal|dev-system-heal-check.sh|Conservative diagnosis, repair plan, autofix, and heal history"
  "openclaw-workspace-detect|dev-openclaw-workspace-detect-check.sh|Read-only detection of configured OpenClaw workspaces"
  "openclaw-real-workspace-profile|dev-openclaw-real-workspace-profile-check.sh|Read-only profile of the real OpenClaw source workspace"
  "openclaw-source-migration-map|dev-openclaw-source-migration-map-check.sh|Read-only migration candidate map for OpenClaw source capabilities"
  "openclaw-source-migration-plan|dev-openclaw-source-migration-plan-check.sh|Plan-only first-wave migration draft for OpenClaw source capabilities"
  "openclaw-plugin-sdk-contract-review|dev-openclaw-plugin-sdk-contract-review-check.sh|Read-only contract review draft for the OpenClaw plugin SDK"
  "openclaw-plugin-sdk-source-review-scope|dev-openclaw-plugin-sdk-source-review-scope-check.sh|Plan-only source review scope for the OpenClaw plugin SDK"
  "openclaw-plugin-sdk-source-content-review|dev-openclaw-plugin-sdk-source-content-review-check.sh|Scoped source content review for the OpenClaw plugin SDK"
  "openclaw-plugin-sdk-native-contract-tests|dev-openclaw-plugin-sdk-native-contract-tests-check.sh|Native contract tests derived from OpenClaw plugin SDK source signals"
  "openclaw-native-plugin-sdk-contract-implementation|dev-openclaw-native-plugin-sdk-contract-implementation-check.sh|Native OpenClaw plugin SDK contract implementation slots"
  "openclaw-tool-catalog|dev-openclaw-tool-catalog-check.sh|Read-only native absorption of the enhanced OpenClaw tool catalog"
  "openclaw-plugin-manifest-map|dev-openclaw-plugin-manifest-map-check.sh|Read-only native absorption of enhanced OpenClaw extension plugin manifests"
  "openclaw-plugin-capability-plan|dev-openclaw-plugin-capability-plan-check.sh|Manifest-derived native OpenClaw plugin capability planning"
  "openclaw-plugin-candidate-contract-tests|dev-openclaw-plugin-candidate-contract-tests-check.sh|Native adapter contract tests for a selected enhanced OpenClaw plugin candidate"
  "openclaw-plugin-search-web-adapter-contract|dev-openclaw-plugin-search-web-adapter-contract-check.sh|Native search/web adapter contract shell for enhanced OpenClaw plugin candidates"
  "openclaw-plugin-search-web-adapter-task|dev-openclaw-plugin-search-web-adapter-task-check.sh|Approval-gated native search/web adapter task materialization"
  "openclaw-plugin-search-web-adapter-denial-recovery|dev-openclaw-plugin-search-web-adapter-denial-recovery-check.sh|Denial and fresh-approval recovery for native search/web adapter tasks"
  "openclaw-plugin-search-web-adapter-runtime-preflight|dev-openclaw-plugin-search-web-adapter-runtime-preflight-check.sh|Runtime preflight envelope for native search/web adapter invocation"
  "openclaw-plugin-search-web-adapter-runtime-activation-plan|dev-openclaw-plugin-search-web-adapter-runtime-activation-plan-check.sh|Plan-only runtime activation gates for native search/web adapter invocation"
  "openclaw-plugin-search-web-adapter-runtime-activation-task|dev-openclaw-plugin-search-web-adapter-runtime-activation-task-check.sh|Approval-gated runtime activation task shell for native search/web adapter invocation"
  "openclaw-plugin-search-web-adapter-runtime-activation-denial-recovery|dev-openclaw-plugin-search-web-adapter-runtime-activation-denial-recovery-check.sh|Denial and fresh-approval recovery for native search/web runtime activation tasks"
  "openclaw-plugin-search-web-adapter-runtime-activation-hardening|dev-openclaw-plugin-search-web-adapter-runtime-activation-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains for native search/web runtime activation tasks"
  "openclaw-plugin-search-web-adapter-runtime-activation-persistence|dev-openclaw-plugin-search-web-adapter-runtime-activation-persistence-check.sh|Restart persistence for native search/web runtime activation approval and recovery chains"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-check.sh|Provider runtime sandbox contract for native search/web adapter invocation"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox-task|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-task-check.sh|Approval-gated provider runtime sandbox task shell for native search/web adapter invocation"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox-denial-recovery|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-denial-recovery-check.sh|Denial and fresh-approval recovery for native search/web provider sandbox tasks"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox-hardening|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains for native search/web provider sandbox tasks"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox-persistence|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-persistence-check.sh|Restart persistence for native search/web provider sandbox approval and recovery chains"
  "openclaw-plugin-search-web-adapter-provider-runtime-sandbox-regression|dev-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-regression-check.sh|Focused regression for native search/web provider sandbox approval and recovery chains"
  "openclaw-native-plugin-contract|dev-openclaw-native-plugin-contract-check.sh|Native OpenClaw plugin and capability contract skeleton"
  "openclaw-native-plugin-registry|dev-openclaw-native-plugin-registry-check.sh|Native OpenClaw plugin contract registry"
  "openclaw-formal-integration-readiness|dev-openclaw-formal-integration-readiness-check.sh|Governed readiness gate for formal OpenClaw source integration"
  "openclaw-native-plugin-adapter|dev-openclaw-native-plugin-adapter-check.sh|Native OpenClaw plugin adapter shell for manifest profiling"
  "openclaw-native-tool-catalog-adapter|dev-openclaw-native-tool-catalog-adapter-check.sh|Native adapter invocation for read-only OpenClaw tool catalog queries"
  "openclaw-native-workspace-semantic-index|dev-openclaw-native-workspace-semantic-index-check.sh|Native read-only semantic index for enhanced OpenClaw workspace files"
  "openclaw-native-workspace-symbol-lookup|dev-openclaw-native-workspace-symbol-lookup-check.sh|Governed read-only executable symbol lookup for enhanced OpenClaw workspace files"
  "openclaw-native-workspace-text-write|dev-openclaw-native-workspace-text-write-check.sh|Approval-gated native OpenClaw workspace text write adapter"
  "openclaw-native-workspace-patch-apply|dev-openclaw-native-workspace-patch-apply-check.sh|Diff-preview approval-gated native OpenClaw workspace patch adapter"
  "openclaw-native-workspace-multi-patch|dev-openclaw-native-workspace-multi-patch-check.sh|Multi-hunk diff-preview approval-gated native OpenClaw workspace patch adapter"
  "openclaw-native-workspace-patch-validation|dev-openclaw-native-workspace-patch-validation-check.sh|Structured validation for native OpenClaw workspace patch safety"
  "openclaw-native-workspace-structured-edit|dev-openclaw-native-workspace-structured-edit-check.sh|Structured line-edit proposal support for native OpenClaw workspace patches"
  "openclaw-native-workspace-edit-proposal|dev-openclaw-native-workspace-edit-proposal-check.sh|Proposal envelope metadata for native OpenClaw workspace edits"
  "openclaw-source-derived-edit-proposal|dev-openclaw-source-derived-edit-proposal-check.sh|Source-derived proposal envelopes from enhanced OpenClaw tool signals"
  "openclaw-workspace-edit-target-selection|dev-openclaw-workspace-edit-target-selection-check.sh|Bounded real OpenClaw workspace target selection for source-derived edit proposals"
  "openclaw-prompt-semantics-edit-plan|dev-openclaw-prompt-semantics-edit-plan-check.sh|Prompt/tool semantics-derived edit intent and expected checks for OpenClaw workspace proposals"
  "openclaw-rationale-check-bundle|dev-openclaw-rationale-check-bundle-check.sh|Structured rationale, check, and risk bundles for source-derived OpenClaw edit proposals"
  "openclaw-source-authored-edit-task|dev-openclaw-source-authored-edit-task-check.sh|Approval-gated source-authored OpenClaw edit task entrypoint"
  "openclaw-source-integration-regression|dev-openclaw-source-integration-regression-check.sh|Focused regression for the enhanced OpenClaw source-authored edit integration chain"
  "openclaw-source-command-proposals|dev-openclaw-source-command-proposals-check.sh|Read-only enhanced OpenClaw source-derived shell/process command proposals"
  "openclaw-source-command-plan|dev-openclaw-source-command-plan-check.sh|Plan-only enhanced OpenClaw source-derived shell/process command drafts"
  "openclaw-source-command-task|dev-openclaw-source-command-task-check.sh|Approval-gated enhanced OpenClaw source-derived shell/process command task materialization"
  "openclaw-source-command-execute|dev-openclaw-source-command-execute-check.sh|Approved enhanced OpenClaw source-derived shell/process command execution"
  "openclaw-source-command-denial-recovery|dev-openclaw-source-command-denial-recovery-check.sh|Denial and fresh-approval recovery for enhanced OpenClaw source-derived commands"
  "openclaw-source-command-hardening|dev-openclaw-source-command-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains for enhanced OpenClaw source-derived commands"
  "openclaw-source-command-persistence|dev-openclaw-source-command-persistence-check.sh|Restart persistence for enhanced OpenClaw source-derived command recovery chains"
  "openclaw-source-command-regression|dev-openclaw-source-command-regression-check.sh|Focused regression for the enhanced OpenClaw source-derived command integration chain"
  "openclaw-native-plugin-invoke-plan|dev-openclaw-native-plugin-invoke-plan-check.sh|Plan-only approval gate for native OpenClaw plugin invocation"
  "openclaw-native-plugin-invoke-task|dev-openclaw-native-plugin-invoke-task-check.sh|Approval-gated task materialization for native OpenClaw plugin invocation"
  "openclaw-native-plugin-invoke-deferred|dev-openclaw-native-plugin-invoke-deferred-check.sh|Runtime-adapter deferred execution boundary for approved native OpenClaw plugin invocation"
  "openclaw-native-plugin-runtime-preflight|dev-openclaw-native-plugin-runtime-preflight-check.sh|Runtime preflight envelope for native OpenClaw plugin invocation"
  "openclaw-native-plugin-runtime-activation-plan|dev-openclaw-native-plugin-runtime-activation-plan-check.sh|Plan-only runtime activation gates for native OpenClaw plugin invocation"
  "openclaw-native-plugin-runtime-activation-task|dev-openclaw-native-plugin-runtime-activation-task-check.sh|Approval-gated runtime activation task shell for native OpenClaw plugin invocation"
  "openclaw-native-plugin-runtime-activation-denial-recovery|dev-openclaw-native-plugin-runtime-activation-denial-recovery-check.sh|Denial and fresh-approval recovery for native OpenClaw plugin runtime activation tasks"
  "openclaw-native-plugin-runtime-activation-hardening|dev-openclaw-native-plugin-runtime-activation-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains for native OpenClaw plugin runtime activation tasks"
  "openclaw-native-plugin-runtime-activation-persistence|dev-openclaw-native-plugin-runtime-activation-persistence-check.sh|Restart persistence for native OpenClaw plugin runtime activation approval and recovery chains"
  "openclaw-native-plugin-runtime-activation-regression|dev-openclaw-native-plugin-runtime-activation-regression-check.sh|Focused regression for native OpenClaw plugin runtime activation approval and recovery chains"
  "openclaw-native-plugin-runtime-adapter-contract|dev-openclaw-native-plugin-runtime-adapter-contract-check.sh|Native runtime adapter contract shell before OpenClaw plugin module loading"
  "openclaw-native-plugin-runtime-adapter-task|dev-openclaw-native-plugin-runtime-adapter-task-check.sh|Approval-gated native runtime adapter implementation task shell"
  "openclaw-native-plugin-runtime-adapter-denial-recovery|dev-openclaw-native-plugin-runtime-adapter-denial-recovery-check.sh|Denial and fresh-approval recovery for native runtime adapter implementation tasks"
  "openclaw-native-plugin-runtime-adapter-hardening|dev-openclaw-native-plugin-runtime-adapter-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains for native runtime adapter implementation tasks"
  "openclaw-native-plugin-runtime-adapter-persistence|dev-openclaw-native-plugin-runtime-adapter-persistence-check.sh|Restart persistence for native runtime adapter implementation approval and recovery chains"
  "openclaw-workspace-command-proposals|dev-openclaw-workspace-command-proposals-check.sh|Proposal-only command shapes for detected OpenClaw workspaces"
  "openclaw-workspace-command-plan|dev-openclaw-workspace-command-plan-check.sh|Plan-only execution drafts for OpenClaw workspace command proposals"
  "openclaw-workspace-command-task|dev-openclaw-workspace-command-task-check.sh|Approval-gated task materialization for OpenClaw workspace commands"
  "openclaw-workspace-command-execute|dev-openclaw-workspace-command-execute-check.sh|Approved execution of allowlisted OpenClaw workspace commands"
  "openclaw-workspace-command-failure|dev-openclaw-workspace-command-failure-check.sh|Failure capture for approved OpenClaw workspace commands"
  "openclaw-workspace-command-denial|dev-openclaw-workspace-command-denial-check.sh|Denial safety for approval-gated OpenClaw workspace commands"
  "openclaw-workspace-command-denial-recovery|dev-openclaw-workspace-command-denial-recovery-check.sh|Recovery of denied OpenClaw workspace commands behind fresh approval"
  "openclaw-workspace-command-hardening|dev-openclaw-workspace-command-hardening-check.sh|Approval expiry, duplicate clicks, duplicate recovery, and recovery chains"
  "openclaw-workspace-command-recovery|dev-openclaw-workspace-command-recovery-check.sh|Recovery of failed OpenClaw workspace commands behind fresh approval"
  "openclaw-workspace-command-recovery-persistence|dev-openclaw-workspace-command-recovery-persistence-check.sh|Restart persistence for recovered OpenClaw workspace command chains"
  "observer-capability-plan|dev-observer-capability-plan-check.sh|Observer visibility for capability-aware plan metadata"
  "observer-capability-invoke|dev-observer-capability-invoke-check.sh|Observer controls for policy-governed capability invocation"
  "observer-capability-history|dev-observer-capability-history-check.sh|Observer visibility for persistent capability invocation history"
  "observer-command-transcript|dev-observer-command-transcript-check.sh|Observer visibility for sovereign command transcripts"
  "observer-command-ledger|dev-observer-command-ledger-check.sh|Observer visibility for sovereign command transcript ledger"
  "observer-sovereign-maintenance|dev-observer-sovereign-maintenance-check.sh|Observer visibility for sovereign maintenance policy, ticks, and runs"
  "observer-sovereign-maintenance-control|dev-observer-sovereign-maintenance-control-check.sh|Observer controls for sovereign maintenance ticks"
  "observer-filesystem-ledger|dev-observer-filesystem-ledger-check.sh|Observer visibility for sovereign filesystem change ledger"
  "observer-filesystem-read-ledger|dev-observer-filesystem-read-ledger-check.sh|Observer visibility for sovereign filesystem read access ledger"
  "observer-workspace-detect|dev-observer-workspace-detect-check.sh|Observer visibility for read-only OpenClaw workspace detection"
  "observer-openclaw-source-migration-map|dev-observer-openclaw-source-migration-map-check.sh|Observer visibility for OpenClaw source migration candidates"
  "observer-openclaw-source-migration-plan|dev-observer-openclaw-source-migration-plan-check.sh|Observer visibility for plan-only OpenClaw source migration drafts"
  "observer-openclaw-plugin-sdk-contract-review|dev-observer-openclaw-plugin-sdk-contract-review-check.sh|Observer visibility for OpenClaw plugin SDK contract reviews"
  "observer-openclaw-plugin-sdk-source-review-scope|dev-observer-openclaw-plugin-sdk-source-review-scope-check.sh|Observer visibility for OpenClaw plugin SDK source review scopes"
  "observer-openclaw-plugin-sdk-source-content-review|dev-observer-openclaw-plugin-sdk-source-content-review-check.sh|Observer visibility for OpenClaw plugin SDK source content reviews"
  "observer-openclaw-plugin-sdk-native-contract-tests|dev-observer-openclaw-plugin-sdk-native-contract-tests-check.sh|Observer visibility for OpenClaw plugin SDK native contract tests"
  "observer-openclaw-native-plugin-sdk-contract-implementation|dev-observer-openclaw-native-plugin-sdk-contract-implementation-check.sh|Observer visibility for native OpenClaw plugin SDK contract implementation"
  "observer-openclaw-tool-catalog|dev-observer-openclaw-tool-catalog-check.sh|Observer visibility for read-only enhanced OpenClaw tool catalog absorption"
  "observer-openclaw-plugin-manifest-map|dev-observer-openclaw-plugin-manifest-map-check.sh|Observer visibility for read-only enhanced OpenClaw extension plugin manifests"
  "observer-openclaw-plugin-capability-plan|dev-observer-openclaw-plugin-capability-plan-check.sh|Observer visibility for manifest-derived native OpenClaw plugin capability planning"
  "observer-openclaw-plugin-candidate-contract-tests|dev-observer-openclaw-plugin-candidate-contract-tests-check.sh|Observer visibility for selected enhanced OpenClaw plugin candidate contract tests"
  "observer-openclaw-plugin-search-web-adapter-contract|dev-observer-openclaw-plugin-search-web-adapter-contract-check.sh|Observer visibility for native search/web adapter contract shell"
  "observer-openclaw-plugin-search-web-adapter-task|dev-observer-openclaw-plugin-search-web-adapter-task-check.sh|Observer controls for approval-gated native search/web adapter tasks"
  "observer-openclaw-plugin-search-web-adapter-denial-recovery|dev-observer-openclaw-plugin-search-web-adapter-denial-recovery-check.sh|Observer visibility for denied and recovered native search/web adapter tasks"
  "observer-openclaw-plugin-search-web-adapter-runtime-preflight|dev-observer-openclaw-plugin-search-web-adapter-runtime-preflight-check.sh|Observer visibility for native search/web adapter runtime preflight envelopes"
  "observer-openclaw-plugin-search-web-adapter-runtime-activation-plan|dev-observer-openclaw-plugin-search-web-adapter-runtime-activation-plan-check.sh|Observer visibility for native search/web adapter runtime activation gates"
  "observer-openclaw-plugin-search-web-adapter-runtime-activation-task|dev-observer-openclaw-plugin-search-web-adapter-runtime-activation-task-check.sh|Observer controls for approval-gated native search/web runtime activation tasks"
  "observer-openclaw-plugin-search-web-adapter-runtime-activation-denial-recovery|dev-observer-openclaw-plugin-search-web-adapter-runtime-activation-denial-recovery-check.sh|Observer visibility for denied and recovered native search/web runtime activation tasks"
  "observer-openclaw-plugin-search-web-adapter-runtime-activation-hardening|dev-observer-openclaw-plugin-search-web-adapter-runtime-activation-hardening-check.sh|Observer visibility for hardened native search/web runtime activation recovery chains"
  "observer-openclaw-plugin-search-web-adapter-runtime-activation-persistence|dev-observer-openclaw-plugin-search-web-adapter-runtime-activation-persistence-check.sh|Observer visibility for persisted native search/web runtime activation recovery chains"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-check.sh|Observer visibility for native search/web provider runtime sandbox contracts"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-task|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-task-check.sh|Observer controls for approval-gated native search/web provider sandbox tasks"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-denial-recovery|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-denial-recovery-check.sh|Observer visibility for denied and recovered native search/web provider sandbox tasks"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-hardening|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-hardening-check.sh|Observer visibility for hardened native search/web provider sandbox recovery chains"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-persistence|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-persistence-check.sh|Observer visibility for persisted native search/web provider sandbox recovery chains"
  "observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-regression|dev-observer-openclaw-plugin-search-web-adapter-provider-runtime-sandbox-regression-check.sh|Observer focused regression for native search/web provider sandbox approval and recovery chains"
  "observer-openclaw-native-plugin-contract|dev-observer-openclaw-native-plugin-contract-check.sh|Observer visibility for native OpenClaw plugin contracts"
  "observer-openclaw-formal-integration-readiness|dev-observer-openclaw-formal-integration-readiness-check.sh|Observer visibility for formal OpenClaw integration readiness"
  "observer-openclaw-native-plugin-adapter|dev-observer-openclaw-native-plugin-adapter-check.sh|Observer visibility for native OpenClaw plugin adapter shell"
  "observer-openclaw-native-tool-catalog-adapter|dev-observer-openclaw-native-tool-catalog-adapter-check.sh|Observer visibility for native OpenClaw tool catalog adapter invocation"
  "observer-openclaw-native-workspace-semantic-index|dev-observer-openclaw-native-workspace-semantic-index-check.sh|Observer visibility for native OpenClaw workspace semantic index"
  "observer-openclaw-native-workspace-symbol-lookup|dev-observer-openclaw-native-workspace-symbol-lookup-check.sh|Observer visibility for governed native OpenClaw workspace symbol lookup"
  "observer-openclaw-native-workspace-text-write|dev-observer-openclaw-native-workspace-text-write-check.sh|Observer controls for approval-gated native OpenClaw workspace text writes"
  "observer-openclaw-native-workspace-patch-apply|dev-observer-openclaw-native-workspace-patch-apply-check.sh|Observer controls for diff-preview approval-gated native OpenClaw workspace patches"
  "observer-openclaw-native-workspace-multi-patch|dev-observer-openclaw-native-workspace-multi-patch-check.sh|Observer controls for multi-hunk diff-preview approval-gated native OpenClaw workspace patches"
  "observer-openclaw-native-workspace-patch-validation|dev-observer-openclaw-native-workspace-patch-validation-check.sh|Observer visibility for native OpenClaw workspace patch validation safety"
  "observer-openclaw-native-workspace-structured-edit|dev-observer-openclaw-native-workspace-structured-edit-check.sh|Observer visibility for structured line-edit native OpenClaw workspace patches"
  "observer-openclaw-native-workspace-edit-proposal|dev-observer-openclaw-native-workspace-edit-proposal-check.sh|Observer visibility for native OpenClaw workspace edit proposal envelopes"
  "observer-openclaw-source-derived-edit-proposal|dev-observer-openclaw-source-derived-edit-proposal-check.sh|Observer visibility for source-derived OpenClaw edit proposal envelopes"
  "observer-openclaw-workspace-edit-target-selection|dev-observer-openclaw-workspace-edit-target-selection-check.sh|Observer visibility for bounded OpenClaw workspace edit target selection"
  "observer-openclaw-prompt-semantics-edit-plan|dev-observer-openclaw-prompt-semantics-edit-plan-check.sh|Observer visibility for prompt/tool semantics-derived edit plans"
  "observer-openclaw-rationale-check-bundle|dev-observer-openclaw-rationale-check-bundle-check.sh|Observer visibility for source-derived OpenClaw rationale, check, and risk bundles"
  "observer-openclaw-source-authored-edit-task|dev-observer-openclaw-source-authored-edit-task-check.sh|Observer controls for approval-gated source-authored OpenClaw edit tasks"
  "observer-openclaw-source-integration-regression|dev-observer-openclaw-source-integration-regression-check.sh|Observer focused regression for the enhanced OpenClaw source-authored edit integration chain"
  "observer-openclaw-source-command-proposals|dev-observer-openclaw-source-command-proposals-check.sh|Observer visibility for enhanced OpenClaw source-derived shell/process command proposals"
  "observer-openclaw-source-command-plan|dev-observer-openclaw-source-command-plan-check.sh|Observer visibility for enhanced OpenClaw source-derived shell/process command plans"
  "observer-openclaw-source-command-task|dev-observer-openclaw-source-command-task-check.sh|Observer controls for approval-gated enhanced OpenClaw source-derived command tasks"
  "observer-openclaw-source-command-execute|dev-observer-openclaw-source-command-execute-check.sh|Observer visibility for approved enhanced OpenClaw source-derived command execution"
  "observer-openclaw-source-command-denial-recovery|dev-observer-openclaw-source-command-denial-recovery-check.sh|Observer visibility for denied and recovered enhanced OpenClaw source-derived commands"
  "observer-openclaw-source-command-hardening|dev-observer-openclaw-source-command-hardening-check.sh|Observer visibility for hardened enhanced OpenClaw source-derived command recovery chains"
  "observer-openclaw-source-command-persistence|dev-observer-openclaw-source-command-persistence-check.sh|Observer visibility for persisted enhanced OpenClaw source-derived command recovery chains"
  "observer-openclaw-source-command-regression|dev-observer-openclaw-source-command-regression-check.sh|Observer focused regression for the enhanced OpenClaw source-derived command integration chain"
  "observer-openclaw-native-plugin-invoke-plan|dev-observer-openclaw-native-plugin-invoke-plan-check.sh|Observer visibility for native OpenClaw plugin invocation plans"
  "observer-openclaw-native-plugin-invoke-task|dev-observer-openclaw-native-plugin-invoke-task-check.sh|Observer controls for native OpenClaw plugin invocation task materialization"
  "observer-openclaw-native-plugin-invoke-deferred|dev-observer-openclaw-native-plugin-invoke-deferred-check.sh|Observer visibility for runtime-adapter deferred native OpenClaw plugin invocation"
  "observer-openclaw-native-plugin-runtime-preflight|dev-observer-openclaw-native-plugin-runtime-preflight-check.sh|Observer visibility for native OpenClaw plugin runtime preflight envelopes"
  "observer-openclaw-native-plugin-runtime-activation-plan|dev-observer-openclaw-native-plugin-runtime-activation-plan-check.sh|Observer visibility for native OpenClaw plugin runtime activation gates"
  "observer-openclaw-native-plugin-runtime-activation-task|dev-observer-openclaw-native-plugin-runtime-activation-task-check.sh|Observer controls for approval-gated native OpenClaw plugin runtime activation tasks"
  "observer-openclaw-native-plugin-runtime-activation-denial-recovery|dev-observer-openclaw-native-plugin-runtime-activation-denial-recovery-check.sh|Observer visibility for denied and recovered native OpenClaw plugin runtime activation tasks"
  "observer-openclaw-native-plugin-runtime-activation-hardening|dev-observer-openclaw-native-plugin-runtime-activation-hardening-check.sh|Observer visibility for hardened native OpenClaw plugin runtime activation recovery chains"
  "observer-openclaw-native-plugin-runtime-activation-persistence|dev-observer-openclaw-native-plugin-runtime-activation-persistence-check.sh|Observer visibility for persisted native OpenClaw plugin runtime activation recovery chains"
  "observer-openclaw-native-plugin-runtime-activation-regression|dev-observer-openclaw-native-plugin-runtime-activation-regression-check.sh|Observer focused regression for native OpenClaw plugin runtime activation approval and recovery chains"
  "observer-openclaw-native-plugin-runtime-adapter-contract|dev-observer-openclaw-native-plugin-runtime-adapter-contract-check.sh|Observer visibility for native runtime adapter contract shells before plugin module loading"
  "observer-openclaw-native-plugin-runtime-adapter-task|dev-observer-openclaw-native-plugin-runtime-adapter-task-check.sh|Observer controls for approval-gated native runtime adapter implementation tasks"
  "observer-openclaw-native-plugin-runtime-adapter-denial-recovery|dev-observer-openclaw-native-plugin-runtime-adapter-denial-recovery-check.sh|Observer visibility for denied and recovered native runtime adapter implementation tasks"
  "observer-openclaw-native-plugin-runtime-adapter-hardening|dev-observer-openclaw-native-plugin-runtime-adapter-hardening-check.sh|Observer visibility for hardened native runtime adapter implementation recovery chains"
  "observer-openclaw-native-plugin-runtime-adapter-persistence|dev-observer-openclaw-native-plugin-runtime-adapter-persistence-check.sh|Observer visibility for persisted native runtime adapter implementation recovery chains"
  "observer-openclaw-ai-work-view-capture|dev-observer-openclaw-ai-work-view-capture-check.sh|Observer visibility for browser-runtime-backed AI work view capture metadata"
  "observer-openclaw-ai-work-view-capture-summary|dev-observer-openclaw-ai-work-view-capture-summary-check.sh|Observer visibility for structured AI work view capture summaries"
  "observer-openclaw-ai-work-view-task-verification-summary|dev-observer-openclaw-ai-work-view-task-verification-summary-check.sh|Observer visibility for task verification work view summary evidence"
  "observer-openclaw-eye-hand-action-evidence|dev-observer-openclaw-eye-hand-action-evidence-check.sh|Observer visibility for eye-hand action evidence in task verification"
  "observer-openclaw-eye-hand-recovery-evidence|dev-observer-openclaw-eye-hand-recovery-evidence-check.sh|Observer visibility for failed task recovery evidence from eye-hand context"
  "observer-openclaw-eye-hand-auto-recovery-execution|dev-observer-openclaw-eye-hand-auto-recovery-execution-check.sh|Observer visibility for evidence-driven eye-hand auto recovery execution"
  "observer-openclaw-eye-hand-recovery-regression|dev-observer-openclaw-eye-hand-recovery-regression-check.sh|Observer focused regression for the AI work view eye-hand recovery loop"
  "observer-openclaw-mvp-route-alignment|dev-observer-openclaw-mvp-route-alignment-check.sh|Observer visibility for the whitepaper-aligned MVP route checkpoint"
  "observer-openclaw-system-health-self-heal-evidence|dev-observer-openclaw-system-health-self-heal-evidence-check.sh|Observer visibility for conservative body health self-heal evidence"
  "observer-openclaw-mvp-readiness|dev-observer-openclaw-mvp-readiness-check.sh|Observer readiness regression for the first-stage MVP body loop"
  "observer-openclaw-systemd-unit-inventory|dev-observer-openclaw-systemd-unit-inventory-check.sh|Observer visibility for read-only OpenClaw systemd unit inventory"
  "observer-openclaw-systemd-repair-plan|dev-observer-openclaw-systemd-repair-plan-check.sh|Observer visibility for plan-only OpenClaw systemd repair proposals"
  "observer-openclaw-systemd-repair-dry-run|dev-observer-openclaw-systemd-repair-dry-run-check.sh|Observer visibility for OpenClaw systemd repair dry-run envelopes"
  "observer-openclaw-systemd-repair-execution-task|dev-observer-openclaw-systemd-repair-execution-task-check.sh|Observer controls for approval-gated OpenClaw systemd repair execution task shells"
  "observer-openclaw-systemd-repair-approved-deferred|dev-observer-openclaw-systemd-repair-approved-deferred-check.sh|Observer visibility for approved but deferred OpenClaw systemd repair execution shells"
  "observer-openclaw-systemd-repair-real-execution|dev-observer-openclaw-systemd-repair-real-execution-check.sh|Observer visibility for operator-approved real OpenClaw systemd repair execution attempts"
  "observer-openclaw-systemd-repair-post-verification|dev-observer-openclaw-systemd-repair-post-verification-check.sh|Observer visibility for post-execution OpenClaw systemd repair verification evidence"
  "observer-openclaw-phase-2-repair-demo-status|dev-observer-openclaw-phase-2-repair-demo-status-check.sh|Observer visibility for Phase 2 repair demo status and evidence bundle"
  "observer-openclaw-body-service-dependency-map|dev-observer-openclaw-body-service-dependency-map-check.sh|Observer visibility for read-only OpenClaw body service dependency maps"
  "observer-openclaw-health-trend-summary|dev-observer-openclaw-health-trend-summary-check.sh|Observer visibility for read-only OpenClaw body health trend summaries"
  "observer-openclaw-route-aware-next-action-recommendation|dev-observer-openclaw-route-aware-next-action-recommendation-check.sh|Observer visibility for route-aware OpenClaw body next-action recommendations"
  "observer-openclaw-conservative-recovery-policy-explanation|dev-observer-openclaw-conservative-recovery-policy-explanation-check.sh|Observer visibility for conservative OpenClaw body recovery policy explanations"
  "observer-openclaw-body-governance-readiness|dev-observer-openclaw-body-governance-readiness-check.sh|Observer visibility for Phase 2 Track C body governance readiness"
  "observer-openclaw-body-evidence-timeline|dev-observer-openclaw-body-evidence-timeline-check.sh|Observer visibility for Phase 2 body evidence timeline"
  "observer-openclaw-body-evidence-timeline-readiness|dev-observer-openclaw-body-evidence-timeline-readiness-check.sh|Observer visibility for Phase 2 body evidence timeline readiness"
  "observer-openclaw-body-evidence-ledger-plan|dev-observer-openclaw-body-evidence-ledger-plan-check.sh|Observer visibility for Phase 2 body evidence ledger plan"
  "observer-openclaw-body-evidence-ledger-route-review|dev-observer-openclaw-body-evidence-ledger-route-review-check.sh|Observer visibility for Phase 2 body evidence ledger implementation route review"
  "observer-openclaw-body-evidence-ledger-storage-root-plan|dev-observer-openclaw-body-evidence-ledger-storage-root-plan-check.sh|Observer visibility for Phase 2 body evidence ledger storage root selection"
  "observer-openclaw-body-evidence-ledger-storage-root-route-review|dev-observer-openclaw-body-evidence-ledger-storage-root-route-review-check.sh|Observer visibility for Phase 2 body evidence ledger storage root materialization route review"
  "observer-openclaw-body-evidence-ledger-directory-task|dev-observer-openclaw-body-evidence-ledger-directory-task-check.sh|Observer controls for approval-gated Phase 2 body evidence ledger directory task shells"
  "observer-openclaw-body-evidence-ledger-directory-execution|dev-observer-openclaw-body-evidence-ledger-directory-execution-check.sh|Observer visibility for approved Phase 2 body evidence ledger directory creation"
  "observer-openclaw-body-evidence-ledger-first-record-plan|dev-observer-openclaw-body-evidence-ledger-first-record-plan-check.sh|Observer visibility for Phase 2 body evidence ledger first record plan"
  "observer-openclaw-body-evidence-ledger-first-record-route-review|dev-observer-openclaw-body-evidence-ledger-first-record-route-review-check.sh|Observer visibility for Phase 2 body evidence ledger first record route review"
  "observer-openclaw-body-evidence-ledger-first-record-task|dev-observer-openclaw-body-evidence-ledger-first-record-task-check.sh|Observer controls for approval-gated Phase 2 body evidence ledger first record task shells"
  "observer-openclaw-body-evidence-ledger-first-record-append|dev-observer-openclaw-body-evidence-ledger-first-record-append-check.sh|Observer visibility for approved Phase 2 body evidence ledger first record append"
  "observer-openclaw-body-evidence-ledger-readiness|dev-observer-openclaw-body-evidence-ledger-readiness-check.sh|Observer visibility for Phase 2 body evidence ledger readiness"
  "observer-openclaw-body-evidence-ledger-demo-status|dev-observer-openclaw-body-evidence-ledger-demo-status-check.sh|Observer visibility for Phase 2 body evidence ledger demo status"
  "observer-openclaw-phase-2-route-review|dev-observer-openclaw-phase-2-route-review-check.sh|Observer visibility for whitepaper-aligned Phase 2 route review"
  "observer-openclaw-phase-2-demo-control-room|dev-observer-openclaw-phase-2-demo-control-room-check.sh|Observer visibility for the Phase 2 operator demo control room"
  "observer-openclaw-phase-2-demo-walkthrough|dev-observer-openclaw-phase-2-demo-walkthrough-check.sh|Observer visibility for the Phase 2 human demo walkthrough"
  "observer-openclaw-phase-2-demo-readiness-exit|dev-observer-openclaw-phase-2-demo-readiness-exit-check.sh|Observer visibility for the Phase 2 demo readiness exit gate"
  "observer-openclaw-phase-2-next-capability-route-review|dev-observer-openclaw-phase-2-next-capability-route-review-check.sh|Observer visibility for the next Phase 2 body capability route review"
  "observer-openclaw-systemd-next-repair-scope-review|dev-observer-openclaw-systemd-next-repair-scope-review-check.sh|Observer visibility for next OpenClaw systemd repair scope review"
  "observer-openclaw-systemd-next-repair-plan|dev-observer-openclaw-systemd-next-repair-plan-check.sh|Observer visibility for plan-only next OpenClaw systemd repair scope"
  "observer-openclaw-systemd-next-repair-route-review|dev-observer-openclaw-systemd-next-repair-route-review-check.sh|Observer visibility for next OpenClaw systemd repair route review"
  "observer-openclaw-systemd-next-repair-dry-run|dev-observer-openclaw-systemd-next-repair-dry-run-check.sh|Observer visibility for next OpenClaw systemd repair dry-run envelope"
  "observer-openclaw-systemd-next-repair-task-route|dev-observer-openclaw-systemd-next-repair-task-route-check.sh|Observer visibility for next OpenClaw systemd repair task route"
  "observer-openclaw-systemd-next-repair-task-shell|dev-observer-openclaw-systemd-next-repair-task-shell-check.sh|Observer controls for approval-gated next OpenClaw systemd repair task shells"
  "observer-openclaw-systemd-next-repair-real-execution|dev-observer-openclaw-systemd-next-repair-real-execution-check.sh|Observer visibility for operator-approved next OpenClaw systemd repair execution attempts"
  "observer-openclaw-systemd-repair-candidate-assessment|dev-observer-openclaw-systemd-repair-candidate-assessment-check.sh|Observer visibility for OpenClaw systemd repair candidate assessment"
  "observer-openclaw-systemd-repair-candidate-plan|dev-observer-openclaw-systemd-repair-candidate-plan-check.sh|Observer visibility for plan-only OpenClaw systemd repair candidate scope"
  "observer-openclaw-systemd-repair-candidate-task-route|dev-observer-openclaw-systemd-repair-candidate-task-route-check.sh|Observer visibility for OpenClaw systemd repair candidate task route gate"
  "observer-openclaw-systemd-repair-candidate-task-shell|dev-observer-openclaw-systemd-repair-candidate-task-shell-check.sh|Observer controls for approval-gated OpenClaw systemd repair candidate task shells"
  "observer-openclaw-systemd-repair-candidate-readiness|dev-observer-openclaw-systemd-repair-candidate-readiness-check.sh|Observer visibility for OpenClaw systemd repair candidate block readiness"
  "observer-openclaw-systemd-repair-candidate-route-review|dev-observer-openclaw-systemd-repair-candidate-route-review-check.sh|Observer visibility for OpenClaw systemd repair candidate route review"
  "observer-openclaw-systemd-repair-candidate-demo-status|dev-observer-openclaw-systemd-repair-candidate-demo-status-check.sh|Observer visibility for OpenClaw systemd repair candidate demo status"
  "observer-workspace-command-proposals|dev-observer-workspace-command-proposals-check.sh|Observer visibility for OpenClaw workspace command proposals"
  "observer-workspace-command-plan|dev-observer-workspace-command-plan-check.sh|Observer visibility for OpenClaw workspace command plan drafts"
  "observer-workspace-command-task|dev-observer-workspace-command-task-check.sh|Observer controls for approval-gated OpenClaw workspace command tasks"
  "observer-workspace-command-execute|dev-observer-workspace-command-execute-check.sh|Observer controls and visibility for approved OpenClaw workspace command execution"
  "observer-workspace-command-failure|dev-observer-workspace-command-failure-check.sh|Observer visibility for failed OpenClaw workspace command execution"
  "observer-workspace-command-denial|dev-observer-workspace-command-denial-check.sh|Observer visibility for denied OpenClaw workspace command approvals"
  "observer-workspace-command-denial-recovery|dev-observer-workspace-command-denial-recovery-check.sh|Observer visibility for recovered denied OpenClaw workspace commands"
  "observer-workspace-command-denial-recovery-persistence|dev-observer-workspace-command-denial-recovery-persistence-check.sh|Observer visibility for recovered denied OpenClaw workspace command chains across restarts"
  "observer-workspace-command-recovery|dev-observer-workspace-command-recovery-check.sh|Observer controls and visibility for recovered OpenClaw workspace commands"
  "observer-workspace-command-recovery-persistence|dev-observer-workspace-command-recovery-persistence-check.sh|Observer visibility for recovered OpenClaw workspace command chains across restarts"
  "observer-operator|dev-observer-operator-check.sh|Observer UI planner/operator controls and API wiring"
)

selected_filter="${OPENCLAW_MILESTONE_CHECKS:-}"
started_at="$(date -Iseconds)"
passed=0
failed=0
summary_json="$ARTIFACT_DIR/summary.json"

should_run_check() {
  local name="$1"
  if [[ -z "$selected_filter" ]]; then
    return 0
  fi

  local item=""
  IFS="," read -ra selected_items <<<"$selected_filter"
  for item in "${selected_items[@]}"; do
    item="${item#"${item%%[![:space:]]*}"}"
    item="${item%"${item##*[![:space:]]}"}"
    if [[ "$item" == "$name" ]]; then
      return 0
    fi
  done
  return 1
}

json_escape() {
  node -e 'process.stdout.write(JSON.stringify(process.argv[1]))' "$1"
}

results_json=""

echo "OpenClaw milestone check started at $started_at"
echo "Logs: $ARTIFACT_DIR"
if [[ -n "$selected_filter" ]]; then
  echo "Selected checks: $selected_filter"
fi
echo

for entry in "${checks[@]}"; do
  IFS="|" read -r name script description <<<"$entry"
  if ! should_run_check "$name"; then
    continue
  fi

  log_file="$ARTIFACT_DIR/$name.log"
  start_seconds="$SECONDS"
  echo "==> [$name] $description"

  if bash "$SCRIPT_DIR/$script" >"$log_file" 2>&1; then
    duration=$((SECONDS - start_seconds))
    passed=$((passed + 1))
    echo "    PASS (${duration}s)"
    result="{\"name\":$(json_escape "$name"),\"status\":\"passed\",\"durationSeconds\":$duration,\"log\":$(json_escape "$log_file")}"
  else
    status=$?
    duration=$((SECONDS - start_seconds))
    failed=$((failed + 1))
    echo "    FAIL (${duration}s, exit $status)"
    echo "    Last log lines:"
    tail -n 60 "$log_file" | sed 's/^/      /'
    result="{\"name\":$(json_escape "$name"),\"status\":\"failed\",\"durationSeconds\":$duration,\"exitCode\":$status,\"log\":$(json_escape "$log_file")}"
  fi

  if [[ -z "$results_json" ]]; then
    results_json="$result"
  else
    results_json="$results_json,$result"
  fi
  echo
done

finished_at="$(date -Iseconds)"
total=$((passed + failed))
if (( total == 0 )); then
  echo "No milestone checks matched OPENCLAW_MILESTONE_CHECKS='$selected_filter'." >&2
  exit 1
fi

cat >"$summary_json" <<EOF
{
  "startedAt": "$started_at",
  "finishedAt": "$finished_at",
  "total": $total,
  "passed": $passed,
  "failed": $failed,
  "results": [$results_json]
}
EOF

cat "$summary_json"
echo

if (( failed > 0 )); then
  echo "Milestone check failed. Summary: $summary_json" >&2
  exit 1
fi

echo "Milestone check passed. Summary: $summary_json"
